platform: linux/arm64

pipeline:

  # gitleaks:
  #   image: registry.monotremata.xyz/gitleaks
  #   pull: true
  #   commands:
  #     - gitleaks --source . --verbose --redact detect

  init:
    image: registry.monotremata.xyz/terraform
    pull: true
    commands:
      - terraform init -backend-config="conn_str=$BACKEND_CONN_STR"
    secrets:
      [backend_conn_str]

  plan:
    image: registry.monotremata.xyz/terraform
    pull: true
    commands:
      - terraform plan -out=tfplan
      - terraform show -json tfplan
    environment:
      - HTTP_PROXY=caladan:8888
      - HTTPS_PROXY=caladan:8888
    secrets:
      - linode_token
      - namecheap_api_key

  apply:
    image: registry.monotremata.xyz/terraform
    pull: true
    commands:
      - terraform apply tfplan
    environment:
      - HTTP_PROXY=caladan:8888
      - HTTPS_PROXY=caladan:8888
    secrets: [namecheap_api_key]

  notify:
    image: registry.monotremata.xyz/xmpp-ci
    pull: true
    settings:
      username: "woodpecker@monotremata.xyz"
      recipient: "rilla@monotremata.xyz"
      password:
        from_secret: xmpp_password
    when:
      status: [success, failure]
