platform: linux/arm64

pipeline:

  init:
    image: registry.monotremata.xyz/terraform
    pull: true
    commands:
      - terraform init -backend-config="conn_str=$BACKEND_CONN_STR"
    secrets:
      [backend_conn_str]

  # gitleaks:
  #   image: registry.monotremata.xyz/gitleaks
  #   pull: true
  #   commands:
  #     - gitleaks --source . --verbose --redact detect

  notify:
    image: registry.monotremata.xyz/xmpp-ci
    pull: true
    settings:
      username: "woodpecker@monotremata.xyz"
      recipient: "rilla@monotremata.xyz"
      password:
        from_secret: xmpp_password
    when:
      status: [success, failure]
