pg_user := "terraform"
# pg_host := "pg.monotremata.xyz"
pg_host := "narwhal"
pg_db := "terraform_lan"
pg_port := "5432"

passwd := `pass pg.monotremata.xyz/terraform`
# todo: I'll use this once string interpolation gets implenented in Just https://github.com/casey/just/issues/11
# conn_str := f"postgres://{{pg_user}}:{{passwd}}@{{pg_host}}:{{pg_port}}/{{pg_db}}"

export TF_VAR_hetzner_token := `pass hetzner.com/tokens/suricata`

init:
    terraform init -backend-config="conn_str=postgres://{{pg_user}}:{{passwd}}@{{pg_host}}:{{pg_port}}/{{pg_db}}"

plan *ARGS:
    terraform plan {{ARGS}}

apply *ARGS:
    terraform apply {{ARGS}}

terraform *ARGS:
    terraform {{ARGS}}
